### ISSUE TITLE
Can't generate data

### ISSUE THREAD

**Issue by quaxquax** [waylonflinn/weblas#38]
Unfortunately, I get an error when trying to generate the test data. I updated node.js and pointed to python2.7 but no dice. This is on OSX.

```
bash-3.2# npm run data

> weblas@0.9.1 data /Users/quax/projects/weblas
> node test/data/generate.js

Traceback (most recent call last):
  File "generate.py", line 84, in <module>
    for i in range(len(names)):
```

**Comment by quaxquax** [comment]
This seems to be specific to my OSX environment. On linux (Ubuntu) I was prompted to install the nodejs-legacy package for node, afterwards the "npm run data" step performed without a hitch.

**Comment by quaxquax** [comment]
Unfortunately in Linux I also get stuck at the next step. Although the module "glslify" is installed I get the following error trace:

```
golem@quax-E6410:~/projects/weblas$ npm test
> weblas@0.9.1 test /home/golem/projects/weblas
> browserify test/*.js | testling -x $npm_config_browser

Error: Cannot find module 'glslify' from '/home/golem/projects/weblas'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:48:31
    at processDirs (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:182:39)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:197:13)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:80:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:105:17)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by quaxquax** [comment]
Solve the issue in linux. Had modules such as _glslify_ installed globally.

**Comment by waylonflinn** [comment]
Thanks for the feedback. This part of the project (data generation) is definitely still a bit rough around the edges. I'm glad you were finally able to get it working.
