### ISSUE TITLE
error in $ npm run test

### ISSUE THREAD

**Issue by railsagainstignorance** [waylonflinn/weblas#45]
```
$ npm run test

> weblas@0.9.1 test C:\Users\cgath\dev\railsagainstignorance\weblas
> browserify test/*.js | testling -x $npm_config_browser

Error: Cannot find module 'C:\Users\cgath\dev\railsagainstignorance\weblas\test\*.js' from 'C:\Users\cgath\dev\railsagainstignorance\weblas'
    at C:\Users\cgath\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\cgath\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\cgath\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\cgath\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
'http:' is not recognized as an internal or external command,
operable program or batch file.
Command undefined terminated with non-zero exit code
```

**Comment by railsagainstignorance** [comment]
This was on Windows10.

The workaround was to manually invoke the test:

`$ browserify test/*.js | testling -x start`

**Comment by waylonflinn** [comment]
Thanks for reporting this. I've also run into this issue on Windows. I'm searching for a simple fix, but have yet to find one.
